export {
  PIPELINE_STAGES,
  PIPELINE_STAGE_ORDER,
  DEMO_INTENT,
  DEMO_QUOTES,
  DEMO_ROUTE,
  DEMO_POLICY,
  DEMO_SIMULATION,
  DEMO_EXECUTION,
  DEMO_AUDIT,
  DEMO_METRICS,
  DEMO_RAILS,
  type PipelineStageId,
  type PipelineStageMeta,
  type DemoQuote,
  type DemoRouteHop,
  type DemoPolicyCheck,
  type DemoSimulationLine,
  type DemoExecutionStep,
  type DemoAuditEvent,
  type DemoMetric,
  type DemoSettlementRail,
} from './data/demo-pipeline.js';
